apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rule-engine
  template:
    metadata:
      labels:
        app: rule-engine
    spec:
      containers:
        - name: rule-engine
          image: fraud-detection/rule-engine:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

---
apiVersion: v1
kind: Service
metadata:
  name: rule-engine
spec:
  selector:
    app: rule-engine
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP